version: "3.4"

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - mf-sqldata:/var/opt/mssql

  idserver:
    image: identityserver.core
    build:
      context: .
      dockerfile: ./identity-app/IdentityServer.Core/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
    depends_on:
      - sqldata
    ports:
      - "5050:80"

volumes:
  mf-sqldata:
    external: false
